### ISSUE TITLE
Reporte_Creacion_de libreria

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-tec-design#1]
[Reporte_Creacion_Libreria.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-tec-design/files/14717172/Reporte_Creacion_Libreria.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
En base a la rúbrica, han obtenido 100 puntos de 100, felicidades.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
